services:
  node:
    image: "node:24"
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8080"
    ports: # use if it is necessary to expose the container to the host machine
      - "8080:8080"
    command: "npm start"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
